openapi: 3.0.3
info:
  title: Common parameters
  description: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#path-item-object
  version: 1.0.0
servers:
  - url: https://httpbin.org
paths:
  '/anything/{id}':
    parameters:
      - in: path
        name: id
        schema:
          type: number
        required: true
      - in: header
        name: x-extra-id
        schema:
          type: string
    get:
      summary: Get anything
      responses:
        '200':
          description: OK
    post:
      summary: Post anything
      parameters:
        - '$ref': '#/components/parameters/limitParam'
      responses:
        '200':
          description: OK
  '/anything/{id}/{multiplePathParams}':
    parameters:
      - in: path
        name: id
        schema:
          type: number
        required: true
      - in: path
        name: multiplePathParams
        schema:
          type: string
        required: true
    get:
      summary: Get anything
      responses:
        '200':
          description: OK
  '/anything/{id}/{duplicatePathParams}/{id}':
    parameters:
      - in: path
        name: id
        schema:
          type: number
        required: true
      - in: path
        name: duplicatePathParams
        schema:
          type: string
        required: true
    get:
      summary: Get anything
      responses:
        '200':
          description: OK
components:
  parameters:
    limitParam:
      in: query
      name: limit
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 50
        default: 20
      description: The numbers of items to return.
